inventory/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

store/urls.py
from ast import Delete
from django.urls import path
from . import views
app_name= 'store'
urlpatterns = [
    path('', views.Dashboard, name="dashboard"),

    path('login/', views.Login, name="login"),
    path('logout/', views.Logout, name="logout"),

    path('profile/', views.Profile, name="profile"),
    path('change_password/', views.ChangePassword, name="change_password"),

    path('supplier/', views.SupplierView, name="supplier"),
    path('buyer/', views.BuyerView, name="buyer"),

    path('product/', views.ProductView, name="product"),
    path('category/', views.CategoryView, name="category"),
    path('category/edit/<int:pk>/', views.CategoryEdit, name="category-edit"),
    path('category/update/<int:pk>', views.CategoryEdit, name="category-update"),
    path('category/delete/<int:pk>', views.CategoryDelete, name="category-delete"),
    
    path('sale/', views.AddSaleView, name="sale"),
    path('sale-report/', views.SaleReportView, name="sale-report"),
    path('add-to-cart/', views.AddToCart, name="add-to-cart"),
    path('delete-cart-item/<int:pk>/<int:qty>/<int:product_id>', views.DeleteCartItem, name="delete-cart-item"),
    path('add-sale/', views.AddSale, name="add-sale")

]

store/models.py
from email.policy import default
from pyexpat import model
from secrets import choice
from tokenize import blank_re
from django.db import models
from django.contrib.auth.models import AbstractUser

unit = (
    ('PC', 'PC'),
    ('KG', 'KG')
)

# Create your models here.
class User(AbstractUser):
    @property
    def is_supplier(self):
        if hasattr(self, 'supplier'):
            return True
        return False

    @property
    def is_buyer(self):
        if hasattr(self, 'buyer'):
            return True
        return False
    
    @property
    def is_admin(self):
        if hasattr(self, 'admin'):
            return True
        return False

class Supplier(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=120, unique=True)
    address = models.CharField(max_length=220)
    phone = models.CharField(max_length=11)
    created_date = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.name


class Buyer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=120, unique=True)
    address = models.CharField(max_length=220)
    phone = models.CharField(max_length=11)
    created_date = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.name

class Admin(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=120, unique=True)
    address = models.CharField(max_length=220)
    phone = models.CharField(max_length=11)
    created_date = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.name

class Category(models.Model):
    name = models.CharField(max_length=55, blank=False, null=False)
    slug = models.CharField(max_length=60, blank=False, null=False, unique=True)

    def __str__(self):
        return self.name

class Product(models.Model):
    name = models.CharField(max_length=55, blank=False, null=False)
    price = models.FloatField(blank=False, null=False)
    qty = models.IntegerField(blank=False, null=False)
    unit = models.CharField(choices=unit, default='PC', max_length=15)
    image = models.ImageField(upload_to='images', blank=True, null=False)

    def __str__(self):
        return self.name

class Cart(models.Model):
    seller_id = models.IntegerField(blank=False, null=False)
    product = models.OneToOneField(Product, on_delete=models.CASCADE)
    qty = models.IntegerField(blank=False, null=False)

    @property
    def sub_total(self):
        return self.product.price * self.qty

class Sale(models.Model):
    seller_id = models.IntegerField(blank=False, null=False)
    customer = models.ForeignKey(Buyer, related_name='customer' ,on_delete=models.CASCADE)
    invoice = models.CharField(max_length=100, blank=False, null=True)
    payable = models.FloatField(blank=False, null=False)  
    paid = models.FloatField(blank=False, null=False)
    date = models.DateField()

    def __str__(self):
        return self.invoice

store/forms.py
from django import forms
from django import forms
from .models import *

class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = '__all__'

class AddToCartForm(forms.ModelForm):
    class Meta:
        model = Cart
        fields = '__all__'

store/views.py
from django.shortcuts import redirect, render
from django.contrib.auth.decorators import login_required
from .decorators import unauthenticated_user
from django.contrib.auth import authenticate, logout, login, update_session_auth_hash
from django.contrib import messages
from .models import *
from django.contrib.auth.forms import PasswordChangeForm
from .forms import AddToCartForm, ProductForm
import random
from django.db.models import When, F, Q
from django.db import IntegrityError

# Create your views here.
@login_required
def Dashboard(request):
    total_product = Product.objects.all().count()
    in_stock = Product.objects.filter(
        Q(qty__gte=1)
    ).count()
    warning = Product.objects.filter(
        Q(qty__lte=5) & Q(qty__gte=1)
    ).count()
    out_stock = Product.objects.filter(
        Q(qty=0)
    ).count()
    context = {
        'total_product' : total_product,
        'in_stock' : in_stock,
        'warning' : warning,
        'out_stock' : out_stock
    }
    return render(request, 'dashboard.html', context)

@unauthenticated_user
def Login(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('store:dashboard')
        else:
            messages.info(request, 'Username or password is incorrect')
    return render(request, 'login.html')

@login_required
def Logout(request):
    logout(request)
    return redirect('store:login')

@login_required
def Profile(request):
    if request.user.is_admin:
        user_data = {
            'name' : request.user.admin.name,
            'address' : request.user.admin.address,
            'phone' : request.user.admin.phone,
            'email' : request.user.email,
        }
    elif request.user.is_buyer:
        user_data = {
            'name' : request.user.buyer.name,
            'address' : request.user.buyer.address,
            'phone' : request.user.buyer.phone,
            'email' : request.user.email,
        }
    elif request.user.is_supplier:
        user_data = {
            'name' : request.user.supplier.name,
            'address' : request.user.supplier.address,
            'phone' : request.user.supplier.phone,
            'email' : request.user.email,
        }
    context = {
        'user':user_data
    }

    if request.method=='POST':
        name = request.POST['name']
        phone = request.POST['phone']
        address = request.POST['address']
        email = request.POST['email']
        user = User.objects.get(id=request.user.id)
        user.email = email
        user.save()
        if request.user.is_admin:
            profile = Admin.objects.get(user=request.user)
        elif request.user.is_buyer:
            profile = Buyer.objects.get(user=request.user)
        elif request.user.is_supplier:
            profile = Supplier.objects.get(user=request.user)
        profile.name = name
        profile.phone = phone
        profile.address = address
        profile.save()
        return redirect('store:profile')

    return render(request, 'profile.html', context)

@login_required()
def ChangePassword(request):

    old_password = request.POST['old_password']
    new_password1 = request.POST['new_password1']
    new_password2 = request.POST['new_password2']
    user = authenticate(username=request.user, password=old_password)
    if user is not None:
        if new_password1 != new_password2:
            messages.info(request, "retype password not matched!")
        else:
            u = User.objects.get(username=request.user)
            u.set_password(new_password1)
            u.save()
            messages.info(request, "Password changes")
    else:
        messages.info(request, "Old password in not correct")
    return redirect('store:profile')

@login_required
def SupplierView(request):
    if request.method=='POST':
        name = request.POST['name']
        email = request.POST['email']
        phone = request.POST['phone']
        address = request.POST['address']
        rand = str(random.randint(1000,9999))
        username = name.split(" ",)[-1].lower()+ rand
        password = name.split(" ",)[-1].lower()+ rand
        user = User.objects.create_user(
            username=username, password=password, email=email
        )
        Supplier.objects.create(
            user = user, name = name, phone=phone, address=address
        )
    supplier_list = Supplier.objects.all()
    context = {
        'supplier': supplier_list
    }
        
    return render(request, 'supplier.html', context)

@login_required
def BuyerView(request):
    if request.method=='POST':
        name = request.POST['name']
        email = request.POST['email']
        phone = request.POST['phone']
        address = request.POST['address']
        rand = str(random.randint(1000,9999))
        username = name.split(" ",)[-1].lower()+ rand
        password = name.split(" ",)[-1].lower()+ rand
        user = User.objects.create_user(
            username=username, password=password, email=email
        )
        Buyer.objects.create(
            user = user, name = name, phone=phone, address=address
        )
    buyer_list = Buyer.objects.all()
    context = {
        'supplier': buyer_list
    }
        
    return render(request, 'buyer.html', context)

@login_required
def CategoryView(request):
    if request.method == 'POST':
        name = request.POST['name']
        slug = name.replace(" ", "-").lower()
        try:
            Category.objects.create(name=name, slug=slug)
        except IntegrityError as e:
            messages.error(request, "Category already exists")
        return redirect('store:category')
    category = Category.objects.all()
    context = {
        'category' : category
    }
    return render(request, "category.html", context)

@login_required
def CategoryDelete(request, pk):
    category = Category.objects.get(id=pk)
    category.delete()
    return redirect('store:category')

@login_required
def CategoryEdit(request, pk):        
    category = Category.objects.get(id=pk)
    if request.method == 'POST': 
        name = request.POST['name']
        slug = name.replace(" ", "-").lower()
        try:
            cat = Category.objects.get(id=pk)
            cat.name = name
            cat.slug = slug
            cat.save()
        except IntegrityError as e:
            messages.error(request, "Category already exists")
        return redirect('store:category')
    context = {
        'category' : category
    }
    return render(request, './edit/category.html', context)


@login_required
def ProductView(request):
    if request.method=='POST':
        form = ProductForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
        return redirect('store:product')
    products = Product.objects.all().order_by('-id')
    context = {
        'products': products
    }
        
    return render(request, 'product.html', context)

@login_required
def AddSaleView(request):
    buyer_list = Buyer.objects.all()
    products = Product.objects.all()
    carts = Cart.objects.filter(seller_id=request.user.id)
    total_price = 0
    for item in carts:
        total_price += item.product.price * item.qty
    context = {
        'customers' : buyer_list,
        'products' : products,
        'carts': carts,
        'total_price': total_price
    }
    return render (request, 'sale.html', context)


@login_required
def AddToCart(request):
    if request.method=='POST':
        product_id = request.POST['product']
        qty = request.POST['qty']
        product = Product.objects.get(id=product_id)
        if (int(product.qty)-int(qty)) < 0:
            messages.info(request, "Not enough in stock")
        else:
            if not Cart.objects.filter(product=product_id).exists():
                form = AddToCartForm(request.POST)
                if form.is_valid:
                    form.save()
                    product.qty = product.qty-int(qty)
                    product.save()
            else:
                messages.info(request, "Product already added")
    return redirect('store:sale')

@login_required
def DeleteCartItem(request, pk, qty, product_id):
    product = Product.objects.get(id=product_id)
    product.qty += qty
    product.save()
    item = Cart.objects.get(id=pk)
    item.delete()
    return redirect('store:sale')

@login_required
def AddSale(request):
    if request.method == 'POST':
        payable = request.POST['payable']
        paid = request.POST['paid']
        customer_id = request.POST['customer']
        date = request.POST['date']
        seller = request.POST['seller_id']
        invoice = str(random.randint(100000,999999))
        if Cart.objects.all().exists():
            Sale.objects.create(
                payable=payable, paid=paid, customer_id=customer_id, date=date, invoice=invoice, seller_id=seller
            )
            Cart.objects.all().delete()
    return redirect('store:sale')

@login_required
def SaleReportView(request):
    sales = Sale.objects.all()
    context = {
        'sales':sales
    }
    return render(request, 'sale_report.html', context)

store/templates/asset/header.html
{% load static %}
<header class="topbar" data-navbarbg="skin5">
    <nav class="navbar top-navbar navbar-expand-md navbar-dark">
        <div class="navbar-header" data-logobg="skin5">
            <!-- ============================================================== -->
            <!-- Logo -->
            <!-- ============================================================== -->
            <a class="navbar-brand" href="index.html">
                <!-- Logo icon -->
                <b class="logo-icon ps-2">
        <!--You can put here icon as well // <i class="wi wi-sunset"></i> //-->
        <!-- Dark Logo icon -->
        <img
          src="{% static '/assets/images/logo-icon.png' %}"
          alt="homepage"
          class="light-logo"
          width="25"
        />
      </b>
                <!--End Logo icon -->
                <!-- Logo text -->
                <span class="logo-text ms-2">
        <!-- dark Logo text -->
        <img
          src="{% static '/assets/images/iv.png' %}"
          alt="homepage"
          class="light-logo"
        />
      </span>
                <!-- Logo icon -->
                <!-- <b class="logo-icon"> -->
                <!--You can put here icon as well // <i class="wi wi-sunset"></i> //-->
                <!-- Dark Logo icon -->
                <!-- <img src="{% static '/assets/images/logo-text.png" alt="homepage" class="light-logo" /> -->

                <!-- </b> -->
                <!--End Logo icon -->
            </a>
            <!-- ============================================================== -->
            <!-- End Logo -->
            <!-- ============================================================== -->
            <!-- ============================================================== -->
            <!-- Toggle which is visible on mobile only -->
            <!-- ============================================================== -->
            <a class="nav-toggler waves-effect waves-light d-block d-md-none" href="javascript:void(0)"><i class="ti-menu ti-close"></i
    ></a>
        </div>
        <!-- ============================================================== -->
        <!-- End Logo -->
        <!-- ============================================================== -->
        <div class="navbar-collapse collapse" id="navbarSupportedContent" data-navbarbg="skin5">
            <!-- ============================================================== -->
            <!-- toggle and nav items -->
            <!-- ============================================================== -->
            <ul class="navbar-nav float-start me-auto">
                <li class="nav-item d-none d-lg-block">
                    <a class="nav-link sidebartoggler waves-effect waves-light" href="javascript:void(0)" data-sidebartype="mini-sidebar"><i class="mdi mdi-menu font-24"></i
        ></a>
            </ul>
            <!-- ============================================================== -->
            <!-- Right side toggle and nav items -->
            <!-- ============================================================== -->
            <ul class="navbar-nav float-end">
                <!-- ============================================================== -->
                <!-- Comment -->
                <!-- ============================================================== -->
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        <i class="mdi mdi-bell font-24"></i>
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item" href="#">Action</a></li>
                        <li><a class="dropdown-item" href="#">Another action</a></li>
                        <li>
                            <hr class="dropdown-divider" />
                        </li>
                        <li>
                            <a class="dropdown-item" href="#">Something else here</a>
                        </li>
                    </ul>
                </li>
                <!-- ============================================================== -->
                <!-- End Comment -->
                <!-- ============================================================== -->
                <!-- ============================================================== -->
                <!-- Messages -->
                <!-- ============================================================== -->
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle waves-effect waves-dark" href="#" id="2" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        <i class="font-24 mdi mdi-comment-processing"></i>
                    </a>
                    <ul class="
            dropdown-menu dropdown-menu-end
            mailbox
            animated
            bounceInDown
          " aria-labelledby="2">
                        <ul class="list-style-none">
                            <li>
                                <div class="">
                                    <!-- Message -->
                                    <a href="javascript:void(0)" class="link border-top">
                                        <div class="d-flex no-block align-items-center p-10">
                                            <span class="
                        btn btn-success btn-circle
                        d-flex
                        align-items-center
                        justify-content-center
                      "><i class="mdi mdi-calendar text-white fs-4"></i
                    ></span>
                                            <div class="ms-2">
                                                <h5 class="mb-0">Event today</h5>
                                                <span class="mail-desc">Just a reminder that event</span
                      >
                    </div>
                  </div>
                </a>
                <!-- Message -->
                <a href="javascript:void(0)" class="link border-top">
                  <div class="d-flex no-block align-items-center p-10">
                    <span
                      class="
                        btn btn-info btn-circle
                        d-flex
                        align-items-center
                        justify-content-center
                      "
                      ><i class="mdi mdi-settings fs-4"></i
                    ></span>
                                                <div class="ms-2">
                                                    <h5 class="mb-0">Settings</h5>
                                                    <span class="mail-desc">You can customize this template</span
                      >
                    </div>
                  </div>
                </a>
                <!-- Message -->
                <a href="javascript:void(0)" class="link border-top">
                  <div class="d-flex no-block align-items-center p-10">
                    <span
                      class="
                        btn btn-primary btn-circle
                        d-flex
                        align-items-center
                        justify-content-center
                      "
                      ><i class="mdi mdi-account fs-4"></i
                    ></span>
                                                    <div class="ms-2">
                                                        <h5 class="mb-0">Pavan kumar</h5>
                                                        <span class="mail-desc">Just see the my admin!</span
                      >
                    </div>
                  </div>
                </a>
                <!-- Message -->
                <a href="javascript:void(0)" class="link border-top">
                  <div class="d-flex no-block align-items-center p-10">
                    <span
                      class="
                        btn btn-danger btn-circle
                        d-flex
                        align-items-center
                        justify-content-center
                      "
                      ><i class="mdi mdi-link fs-4"></i
                    ></span>
                                                        <div class="ms-2">
                                                            <h5 class="mb-0">Luanch Admin</h5>
                                                            <span class="mail-desc">Just see the my new admin!</span
                      >
                    </div>
                  </div>
                </a>
              </div>
            </li>
          </ul>
        </ul>
      </li>
      <!-- ============================================================== -->
      <!-- End Messages -->
      <!-- ============================================================== -->

      <!-- ============================================================== -->
      <!-- User profile and search -->
      <!-- ============================================================== -->
      <li class="nav-item dropdown">
        <a
          class="
            nav-link
            dropdown-toggle
            text-muted
            waves-effect waves-dark
            pro-pic
          "
          href="#"
          id="navbarDropdown"
          role="button"
          data-bs-toggle="dropdown"
          aria-expanded="false"
        >
          <img
            src="{% static '/assets/images/users/1.jpg' %}"
            alt="user"
            class="rounded-circle"
            width="31"
          />
        </a>
        <ul
          class="dropdown-menu dropdown-menu-end user-dd animated"
          aria-labelledby="navbarDropdown"
        >
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="{% url 'store:profile' %}"
            ><i class="mdi mdi-settings me-1 ms-1"></i> Account
            Setting</a
          >
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="{% url 'store:logout' %}"
            ><i class="fa fa-power-off me-1 ms-1"></i> Logout</a
          >
          <div class="dropdown-divider"></div>
          <div class="ps-4 p-10">
            <a
              href="{% url 'store:profile' %}"
              class="btn btn-sm btn-success btn-rounded text-white"
              >View Profile</a
            >
          </div>
        </ul>
      </li>
      <!-- ============================================================== -->
      <!-- User profile and search -->
      <!-- ============================================================== -->
    </ul>
  </div>
</nav>
</header>

store/templates/asset/sidebar.html
{% load static %}
<aside class="left-sidebar" data-sidebarbg="skin5">
    <!-- Sidebar scroll-->
    <div class="scroll-sidebar">
        <!-- Sidebar navigation-->
        <nav class="sidebar-nav">
            <ul id="sidebarnav" class="pt-4">
                <li class="sidebar-item">
                    <a class="sidebar-link waves-effect waves-dark sidebar-link" href="{% url 'store:dashboard' %}" aria-expanded="false"><i class="mdi mdi-view-dashboard"></i><span class="hide-menu">
                        Dashboard</span></a>
                </li>
                <li class="sidebar-item">
                    <a class="sidebar-link has-arrow waves-effect waves-dark" href="javascript:void(0)" aria-expanded="false"><i class="mdi mdi-cart"></i><span class="hide-menu">Product </span></a>
                    <ul aria-expanded="false" class="collapse first-level">
                        <li class="sidebar-item">
                            <a class="sidebar-link waves-effect waves-dark sidebar-link" href="{% url 'store:category' %}" aria-expanded="false"><i class="mdi mdi-application"></i><span class="hide-menu">
                                Category</span></a>
                        </li>
                        <li class="sidebar-item">
                            <a class="sidebar-link waves-effect waves-dark sidebar-link" href="{% url 'store:product' %}" aria-expanded="false"><i class="mdi mdi-cart"></i><span class="hide-menu">
                                Product</span></a>
                        </li>
                        <li class="sidebar-item">
                            <a class="sidebar-link waves-effect waves-dark sidebar-link" href="{% url 'store:supplier' %}" aria-expanded="false"><i class="mdi mdi-account-multiple-minus"></i><span class="hide-menu">
                        Supplier</span></a>
                        </li>
                        <li class="sidebar-item">
                            <a class="sidebar-link waves-effect waves-dark sidebar-link" href="{% url 'store:buyer' %}" aria-expanded="false"><i class="mdi mdi-account-multiple-plus"></i><span class="hide-menu">Customer</span></a>
                        </li>

                    </ul>
                </li>
                <li class="sidebar-item">
                    <a class="sidebar-link has-arrow waves-effect waves-dark" href="javascript:void(0)" aria-expanded="false"><i class="mdi mdi-receipt"></i><span class="hide-menu">Sales </span></a>
                    <ul aria-expanded="false" class="collapse first-level">
                        <li class="sidebar-item">
                            <a class="sidebar-link waves-effect waves-dark sidebar-link" href="{% url 'store:sale' %}" aria-expanded="false"><i class="mdi mdi-receipt"></i><span class="hide-menu">Add Sale</span></a>
                        </li>
                        <li class="sidebar-item">
                            <a class="sidebar-link waves-effect waves-dark sidebar-link" href="{% url 'store:sale-report' %}" aria-expanded="false"><i class="mdi mdi-chart-line"></i><span class="hide-menu">Report</span></a>
                        </li>
                    </ul>
                </li>
            </ul>
        </nav>
        <!-- End Sidebar navigation -->
    </div>
    <!-- End Sidebar scroll-->
</aside>