inventory/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

store/urls.py
from ast import Delete
from django.urls import path
from . import views
app_name= 'store'
urlpatterns = [
    path('', views.Dashboard, name="dashboard"),

    path('login/', views.Login, name="login"),
    path('logout/', views.Logout, name="logout"),

    path('profile/', views.Profile, name="profile"),
    path('change_password/', views.ChangePassword, name="change_password"),

    path('supplier/', views.SupplierView, name="supplier"),
    path('buyer/', views.BuyerView, name="buyer"),

    path('product/', views.ProductView, name="product"),
    path('category/', views.CategoryView, name="category"),
    path('category/edit/<int:pk>/', views.CategoryEdit, name="category-edit"),
    path('category/update/<int:pk>', views.CategoryEdit, name="category-update"),
    path('category/delete/<int:pk>', views.CategoryDelete, name="category-delete"),
    
    path('sale/', views.AddSaleView, name="sale"),
    path('sale-report/', views.SaleReportView, name="sale-report"),
    path('add-to-cart/', views.AddToCart, name="add-to-cart"),
    path('delete-cart-item/<int:pk>/<int:qty>/<int:product_id>', views.DeleteCartItem, name="delete-cart-item"),
    path('add-sale/', views.AddSale, name="add-sale")

]

store/models.py
from email.policy import default
from pyexpat import model
from secrets import choice
from tokenize import blank_re
from django.db import models
from django.contrib.auth.models import AbstractUser

unit = (
    ('PC', 'PC'),
    ('KG', 'KG')
)

# Create your models here.
class User(AbstractUser):
    @property
    def is_supplier(self):
        if hasattr(self, 'supplier'):
            return True
        return False

    @property
    def is_buyer(self):
        if hasattr(self, 'buyer'):
            return True
        return False
    
    @property
    def is_admin(self):
        if hasattr(self, 'admin'):
            return True
        return False

class Supplier(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=120, unique=True)
    address = models.CharField(max_length=220)
    phone = models.CharField(max_length=11)
    created_date = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.name


class Buyer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=120, unique=True)
    address = models.CharField(max_length=220)
    phone = models.CharField(max_length=11)
    created_date = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.name

class Admin(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=120, unique=True)
    address = models.CharField(max_length=220)
    phone = models.CharField(max_length=11)
    created_date = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.name

class Category(models.Model):
    name = models.CharField(max_length=55, blank=False, null=False)
    slug = models.CharField(max_length=60, blank=False, null=False, unique=True)

    def __str__(self):
        return self.name

class Product(models.Model):
    name = models.CharField(max_length=55, blank=False, null=False)
    price = models.FloatField(blank=False, null=False)
    qty = models.IntegerField(blank=False, null=False)
    unit = models.CharField(choices=unit, default='PC', max_length=15)
    image = models.ImageField(upload_to='images', blank=True, null=False)

    def __str__(self):
        return self.name

class Cart(models.Model):
    seller_id = models.IntegerField(blank=False, null=False)
    product = models.OneToOneField(Product, on_delete=models.CASCADE)
    qty = models.IntegerField(blank=False, null=False)

    @property
    def sub_total(self):
        return self.product.price * self.qty

class Sale(models.Model):
    seller_id = models.IntegerField(blank=False, null=False)
    customer = models.ForeignKey(Buyer, related_name='customer' ,on_delete=models.CASCADE)
    invoice = models.CharField(max_length=100, blank=False, null=True)
    payable = models.FloatField(blank=False, null=False)  
    paid = models.FloatField(blank=False, null=False)
    date = models.DateField()

    def __str__(self):
        return self.invoice

store/forms.py
from django import forms
from django import forms
from .models import *

class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = '__all__'

class AddToCartForm(forms.ModelForm):
    class Meta:
        model = Cart
        fields = '__all__'

store/views.py
from django.shortcuts import redirect, render
from django.contrib.auth.decorators import login_required
from .decorators import unauthenticated_user
from django.contrib.auth import authenticate, logout, login, update_session_auth_hash
from django.contrib import messages
from .models import *
from django.contrib.auth.forms import PasswordChangeForm
from .forms import AddToCartForm, ProductForm
import random
from django.db.models import When, F, Q
from django.db import IntegrityError

# Create your views here.
@login_required
def Dashboard(request):
    total_product = Product.objects.all().count()
    in_stock = Product.objects.filter(
        Q(qty__gte=1)
    ).count()
    warning = Product.objects.filter(
        Q(qty__lte=5) & Q(qty__gte=1)
    ).count()
    out_stock = Product.objects.filter(
        Q(qty=0)
    ).count()
    context = {
        'total_product' : total_product,
        'in_stock' : in_stock,
        'warning' : warning,
        'out_stock' : out_stock
    }
    return render(request, 'dashboard.html', context)

@unauthenticated_user
def Login(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('store:dashboard')
        else:
            messages.info(request, 'Username or password is incorrect')
    return render(request, 'login.html')

@login_required
def Logout(request):
    logout(request)
    return redirect('store:login')

@login_required
def Profile(request):
    if request.user.is_admin:
        user_data = {
            'name' : request.user.admin.name,
            'address' : request.user.admin.address,
            'phone' : request.user.admin.phone,
            'email' : request.user.email,
        }
    elif request.user.is_buyer:
        user_data = {
            'name' : request.user.buyer.name,
            'address' : request.user.buyer.address,
            'phone' : request.user.buyer.phone,
            'email' : request.user.email,
        }
    elif request.user.is_supplier:
        user_data = {
            'name' : request.user.supplier.name,
            'address' : request.user.supplier.address,
            'phone' : request.user.supplier.phone,
            'email' : request.user.email,
        }
    context = {
        'user':user_data
    }

    if request.method=='POST':
        name = request.POST['name']
        phone = request.POST['phone']
        address = request.POST['address']
        email = request.POST['email']
        user = User.objects.get(id=request.user.id)
        user.email = email
        user.save()
        if request.user.is_admin:
            profile = Admin.objects.get(user=request.user)
        elif request.user.is_buyer:
            profile = Buyer.objects.get(user=request.user)
        elif request.user.is_supplier:
            profile = Supplier.objects.get(user=request.user)
        profile.name = name
        profile.phone = phone
        profile.address = address
        profile.save()
        return redirect('store:profile')

    return render(request, 'profile.html', context)

@login_required()
def ChangePassword(request):

    old_password = request.POST['old_password']
    new_password1 = request.POST['new_password1']
    new_password2 = request.POST['new_password2']
    user = authenticate(username=request.user, password=old_password)
    if user is not None:
        if new_password1 != new_password2:
            messages.info(request, "retype password not matched!")
        else:
            u = User.objects.get(username=request.user)
            u.set_password(new_password1)
            u.save()
            messages.info(request, "Password changes")
    else:
        messages.info(request, "Old password in not correct")
    return redirect('store:profile')

@login_required
def SupplierView(request):
    if request.method=='POST':
        name = request.POST['name']
        email = request.POST['email']
        phone = request.POST['phone']
        address = request.POST['address']
        rand = str(random.randint(1000,9999))
        username = name.split(" ",)[-1].lower()+ rand
        password = name.split(" ",)[-1].lower()+ rand
        user = User.objects.create_user(
            username=username, password=password, email=email
        )
        Supplier.objects.create(
            user = user, name = name, phone=phone, address=address
        )
    supplier_list = Supplier.objects.all()
    context = {
        'supplier': supplier_list
    }
        
    return render(request, 'supplier.html', context)

@login_required
def BuyerView(request):
    if request.method=='POST':
        name = request.POST['name']
        email = request.POST['email']
        phone = request.POST['phone']
        address = request.POST['address']
        rand = str(random.randint(1000,9999))
        username = name.split(" ",)[-1].lower()+ rand
        password = name.split(" ",)[-1].lower()+ rand
        user = User.objects.create_user(
            username=username, password=password, email=email
        )
        Buyer.objects.create(
            user = user, name = name, phone=phone, address=address
        )
    buyer_list = Buyer.objects.all()
    context = {
        'supplier': buyer_list
    }
        
    return render(request, 'buyer.html', context)

@login_required
def CategoryView(request):
    if request.method == 'POST':
        name = request.POST['name']
        slug = name.replace(" ", "-").lower()
        try:
            Category.objects.create(name=name, slug=slug)
        except IntegrityError as e:
            messages.error(request, "Category already exists")
        return redirect('store:category')
    category = Category.objects.all()
    context = {
        'category' : category
    }
    return render(request, "category.html", context)

@login_required
def CategoryDelete(request, pk):
    category = Category.objects.get(id=pk)
    category.delete()
    return redirect('store:category')

@login_required
def CategoryEdit(request, pk):        
    category = Category.objects.get(id=pk)
    if request.method == 'POST': 
        name = request.POST['name']
        slug = name.replace(" ", "-").lower()
        try:
            cat = Category.objects.get(id=pk)
            cat.name = name
            cat.slug = slug
            cat.save()
        except IntegrityError as e:
            messages.error(request, "Category already exists")
        return redirect('store:category')
    context = {
        'category' : category
    }
    return render(request, './edit/category.html', context)


@login_required
def ProductView(request):
    if request.method=='POST':
        form = ProductForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
        return redirect('store:product')
    products = Product.objects.all().order_by('-id')
    context = {
        'products': products
    }
        
    return render(request, 'product.html', context)

@login_required
def AddSaleView(request):
    buyer_list = Buyer.objects.all()
    products = Product.objects.all()
    carts = Cart.objects.filter(seller_id=request.user.id)
    total_price = 0
    for item in carts:
        total_price += item.product.price * item.qty
    context = {
        'customers' : buyer_list,
        'products' : products,
        'carts': carts,
        'total_price': total_price
    }
    return render (request, 'sale.html', context)


@login_required
def AddToCart(request):
    if request.method=='POST':
        product_id = request.POST['product']
        qty = request.POST['qty']
        product = Product.objects.get(id=product_id)
        if (int(product.qty)-int(qty)) < 0:
            messages.info(request, "Not enough in stock")
        else:
            if not Cart.objects.filter(product=product_id).exists():
                form = AddToCartForm(request.POST)
                if form.is_valid:
                    form.save()
                    product.qty = product.qty-int(qty)
                    product.save()
            else:
                messages.info(request, "Product already added")
    return redirect('store:sale')

@login_required
def DeleteCartItem(request, pk, qty, product_id):
    product = Product.objects.get(id=product_id)
    product.qty += qty
    product.save()
    item = Cart.objects.get(id=pk)
    item.delete()
    return redirect('store:sale')

@login_required
def AddSale(request):
    if request.method == 'POST':
        payable = request.POST['payable']
        paid = request.POST['paid']
        customer_id = request.POST['customer']
        date = request.POST['date']
        seller = request.POST['seller_id']
        invoice = str(random.randint(100000,999999))
        if Cart.objects.all().exists():
            Sale.objects.create(
                payable=payable, paid=paid, customer_id=customer_id, date=date, invoice=invoice, seller_id=seller
            )
            Cart.objects.all().delete()
    return redirect('store:sale')

@login_required
def SaleReportView(request):
    sales = Sale.objects.all()
    context = {
        'sales':sales
    }
    return render(request, 'sale_report.html', context)

store/templates/category.html
{% extends './asset/base.html' %} {% load static %} {% block breadcrumb %}
<div class="page-breadcrumb">
    <div class="row">
        <div class="col-12 d-flex no-block align-items-center">
            <h4 class="page-title">Category</h4>
            <div class="ms-auto text-end">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item active"><a href="{% url 'store:buyer' %}">Category</a></li>
                        <!-- <li class="breadcrumb-item active" aria-current="page"></li> -->
                    </ol>
                </nav>
            </div>
        </div>
    </div>
</div>
{% endblock breadcrumb %} {% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-md-6">
            <div class="card">
                <form class="form-horizontal" method="POST" action="{% url 'store:category' %}">
                    {%csrf_token%}
                    <div class="card-body">
                        <h4 class="card-title">Add Category</h4>
                        <div class="form-group row">
                            <label for="fname" class="col-sm-3 text-end control-label col-form-label">Name</label>
                            <div class="col-sm-9">
                                <input type="text" name="name" class="form-control" id="fname" placeholder="Category name" />
                            </div>
                        </div>
                        <span class="text-danger">{% for message in messages %} {{message}} {% endfor %}</span>
                    </div>
                    <div class="card-body">
                        <button type="submit" class="btn btn-primary">Add</button>
                    </div>
                </form>
            </div>
        </div>
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Basic Datatable</h5>
                    <div class="table-responsive">
                        <table id="zero_config" class="table table-striped table-bordered">
                            <thead>
                                <tr>
                                    <th>Name</th>
                                    <th>Slug</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for item in category %}
                                <tr>
                                    <td>{{item.name}}</td>
                                    <td>{{item.slug}}</td>
                                    <td>
                                        <a href="{% url 'store:category-edit' item.id %}" class="btn btn-sm btn-success text-light"><i class="mdi mdi-table-edit"></i></a>
                                        <a href="{% url 'store:category-delete' item.id %}" onclick="confirm('Are you sure')" class="btn btn-sm btn-danger"><i class="mdi mdi-delete"></i></a>
                                    </td>
                                </tr>
                                {% endfor %}
                            </tbody>
                            <tfoot>
                                <tr>
                                    <th>Name</th>
                                    <th>Slug</th>
                                    <th>Action</th>
                                </tr>
                            </tfoot>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

store/templates/sale.html
{% extends './asset/base.html' %} {% load static %} {% block breadcrumb %}
<div class="page-breadcrumb">
    <div class="row">
        <div class="col-12 d-flex no-block align-items-center">
            <h4 class="page-title">Sale</h4>
            <div class="ms-auto text-end">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item active"><a href="{% url 'store:sale' %}">Sale</a></li>
                        <!-- <li class="breadcrumb-item active" aria-current="page"></li> -->
                    </ol>
                </nav>
            </div>
        </div>
    </div>
</div>
{% endblock breadcrumb %} {% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-md-6">
            <div class="card card-body printableArea">
                <h4 class="card-title">Add To Cart</h4>
                <form class="form-group" method="POST" action="{% url 'store:add-to-cart' %}">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-md-8">
                            <div class="card-body">
                                <div class="form-group row">
                                    <label for="fname" class="col-sm-3 text-end control-label col-form-label">Product</label>
                                    <div class="col-sm-9">
                                        <select required class="select2 form-select shadow-none" name="product">
                                        {% for item in products %}
                                        <option value="{{item.id}}">{{item.name}}</option>
                                        {% endfor %}
                                    </select>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-8">
                            <div class="card-body">
                                <div class="form-group row">
                                    <label for="fname" class="col-sm-3 text-end control-label col-form-label">Qty</label>
                                    <div class="col-sm-9">
                                        <input type="number" class="form-control" value="1" name="qty" />
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% for message in messages %}
                        <p class="text-danger" id="messages">{{message}}</p>
                        {% endfor %}
                        <input type="hidden" value="{{request.user.id}}" name="seller_id" />
                        <button type="submit" class="btn btn-primary">Add to cart</button>
                    </div>
                </form>
            </div>
        </div>
        <div class="col-md-12">
            <div class="card card-body printableArea">
                <h4 class="card-title">Cart Details</h4>
                <div class="row">
                    <div class="col-md-12">
                        <div class="table-responsive mt-5" style="clear: both">
                            <table class="table table-hover">
                                <thead class="thead-light">
                                    <tr>
                                        <th class="text-center">#</th>
                                        <th>Description</th>
                                        <th class="text-end">Quantity</th>
                                        <th class="text-end">Unit Cost</th>
                                        <th class="text-end">Total</th>
                                        <th class="text-end">Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for cart in carts %}
                                    <tr>
                                        <td class="text-center">{{forloop.counter}}</td>
                                        <td>{{cart.product.name}}</td>
                                        <td class="text-end">{{cart.qty}}</td>
                                        <td class="text-end">${{cart.product.price}}</td>
                                        <td class="text-end">${{ cart.sub_total }}</td>
                                        <td class="text-end"><a href="{% url 'store:delete-cart-item' cart.id cart.qty cart.product.id %}" onclick="return confirm('Are you sure?')" class="btn btn-danger btn-sm"><i class="mdi mdi-delete"></i></a></td>
                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="pull-right mt-4 text-end">
                            <p>Sub - Total amount: ${{total_price}}</p>
                            <p>vat (0%) : $0</p>
                            <hr />
                            <h3><b>Total :</b> ${{total_price}}</h3>
                        </div>
                        <div class="clearfix"></div>
                        <hr />
                        <div class="text-end">
                            <button class="btn btn-danger text-white" data-toggle="modal" data-target="#processPayment">Proceed to payment</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="processPayment" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle">Payment Details</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
            </div>
            <form method="POST" action="{% url 'store:add-sale' %}">
                {% csrf_token %}
                <div class="modal-body">
                    <div class="col-md-12">
                        <div class="card-body">
                            <div class="form-group row">
                                <label for="fname" class="col-sm-4 text-end control-label col-form-label">Total Payable</label>
                                <div class="col-sm-8">
                                    <input type="number" disabled value="{{total_price}}" class="form-control" />
                                    <input type="hidden" value="{{total_price}}" name="payable" />
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="card-body">
                            <div class="form-group row">
                                <label for="fname" class="col-sm-4 text-end control-label col-form-label">Cash</label>
                                <div class="col-sm-8">
                                    <input type="number" placeholder="Cash paid" name="paid" class="form-control" />
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="card-body">
                            <div class="form-group row">
                                <label for="fname" class="col-sm-4 text-end control-label col-form-label">Customer</label>
                                <div class="col-sm-8">
                                    <select required class="select2 form-select shadow-none" name="customer">
                                    <option>Select customer</option>
                                    {% for item in customers %}
                                    <option value="{{item.id}}">{{item.name}}</option>
                                    {% endfor %}
                                </select>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="card-body">
                            <div class="form-group row">
                                <label for="fname" class="col-sm-4 text-end control-label col-form-label">Date</label>
                                <div class="col-sm-8">
                                    <input required type="date" class="form-control" name="date" />
                                </div>
                            </div>
                        </div>
                    </div>
                    <input type="hidden" value="{{request.user.admin.id}}" name="seller_id" />
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Add Sale</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

store/templates/sale_report.html
{% extends './asset/base.html' %} {% load static %} {% block breadcrumb %}
<div class="page-breadcrumb">
    <div class="row">
        <div class="col-12 d-flex no-block align-items-center">
            <h4 class="page-title">Supplier</h4>
            <div class="ms-auto text-end">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item active"><a href="{% url 'store:supplier' %}">Supplier</a></li>
                        <!-- <li class="breadcrumb-item active" aria-current="page"></li> -->
                    </ol>
                </nav>
            </div>
        </div>
    </div>
</div>
{% endblock breadcrumb %} {% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Basic Datatable</h5>
                    <div class="table-responsive">
                        <table id="zero_config" class="table table-striped table-bordered">
                            <thead>
                                <tr>
                                    <th>Date</th>
                                    <th>Invoice</th>
                                    <th>Payable</th>
                                    <th>Paid</th>
                                    <th>Customer</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for item in sales %}
                                <tr>
                                    <td>{{item.date}}</td>
                                    <td>{{item.invoice}}</td>
                                    <td>{{item.payable}}</td>
                                    <td>{{item.paid}}</td>
                                    <td>{{item.customer}}</td>
                                </tr>
                                {% endfor %}
                            </tbody>
                            <tfoot>
                                <tr>
                                    <th>Name</th>
                                    <th>Number</th>
                                    <th>Email</th>
                                    <th>Address</th>
                                    <th>Username</th>
                                </tr>
                            </tfoot>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}